spring.application.name=ms-notifications

server.port=5008

spring.datasource.url=jdbc:postgresql://localhost:3008/notifications
spring.datasource.username=notifications
spring.datasource.password=notifications

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
