services:
  #BASE DE DATOS PARA EL MICROSERVICIO DE BOOK
  postgresbook:
    image: postgres:17-alpine
    container_name: book-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
    ports:
      - "3001:5432"
    volumes:
      - postgres_data_book:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U book -d book" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #BASE DE DATOS PARA EL MICROSERVICIO DE USER
  postgresuser:
    image: postgres:17-alpine
    container_name: user-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "3002:5432"
    volumes:
      - postgres_data_user:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d user" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  #BASE DE DATOS PARA EL MICROSERVICIO DE AUTH
  auth-postgres:
    image: postgres:17-alpine
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "3003:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  #BASE DE DATOS PARA EL MICROSERVICIO DE LOANS
  loans-postgres:
    image: postgres:17-alpine
    container_name: loans-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: loans
      POSTGRES_PASSWORD: loans
    ports:
      - "3004:5432"
    volumes:
      - postgres_data_loans:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loans -d loans"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  #BASE DE DATOS PARA EL MICROSERVICIO DE RETURNS
  postgres-returns:
    image: postgres:17-alpine
    container_name: postgres-returns
    environment:
      POSTGRES_DB: returns
      POSTGRES_USER: returns
      POSTGRES_PASSWORD: returns
    ports:
      - "3005:5432"
    volumes:
      - returns_data:/var/lib/postgresql/data
  
  #BASE DE DATOS PARA EL MICROSERVICIO DE RESERVATIONS
  postgres-reservations:
    image: postgres:17-alpine
    container_name: postgres-reservations
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: reservations
      POSTGRES_PASSWORD: reservations
    ports:
      - "3006:5432"
    volumes:
      - reservations_data:/var/lib/postgresql/data
  
  #BASE DE DATOS PARA MICROSERVICIO DE FINE
  postgres-fine:
    image: postgres:17-alpine
    container_name: postgres-fine
    environment:
      POSTGRES_DB: fine
      POSTGRES_USER: fine
      POSTGRES_PASSWORD: fine
    ports:
      - "3007:5432"
    volumes:
      - fine_data:/var/lib/postgresql/data
    
  #BASE DE DATOS PARA EL MICROSERVICIO DE NOTIFICATIONS
  postgres-notifications:
    image: postgres:17-alpine
    container_name: postgres-notifications
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notifications
      POSTGRES_PASSWORD: notifications
    ports:
      - "3008:5432"
    volumes:
      - notifications_data:/var/lib/postgresql/data

volumes:
  postgres_data_book:
  postgres_data_user:
  auth_postgres_data:
  fine_data:
  postgres_data_loans:
  returns_data:
  reservations_data:
  notifications_data: