@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YWxhbGEzQGdtYWlsLmNsIiwiaWF0IjoxNzgzODg0NjA3LCJleHAiOjE3ODM5NzEwMDd9.oI6KhpRe8tLF5WlIdb9-eHsj65tdo9k2qgBruYT7d24

@bookId = 7abe5468-bf54-4fc7-879d-15f3bbc28ea3

@userId = 6c04130a-4e21-4392-9d15-965de545efee

@loanId = befa574a-548e-423d-8074-e8d1a9bd4609

### Login publico
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "walala3@gmail.cl",
  "password": "abcd.1234"
}

### Register publico
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "walala3@gmail.cl",
  "password": "abcd.1234"
}

### Listar libros protegido
GET {{baseUrl}}/books
Authorization: Bearer {{token}}

### Buscar libros por título protegido
GET {{baseUrl}}/books/search?title=Clean
Authorization: Bearer {{token}}

### Buscar libros por autor protegido
GET {{baseUrl}}/books/search?author=bryan
Authorization: Bearer {{token}}

### Buscar libros por ISBN protegido
GET {{baseUrl}}/books/search?isbn=9780201633610
Authorization: Bearer {{token}}

### Crear libro protegido
POST {{baseUrl}}/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "en busca de la felicidad222222",
  "author": "bryansss",
  "category": "lecturaadas",
  "isbn": "44545345"
}

### Obtener libro por id protegido
GET {{baseUrl}}/books/{{bookId}}
Authorization: Bearer {{token}}

### Actualizar libro por id protegido
PUT {{baseUrl}}/books/{{bookId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "refactoring 2 ",
  "author": "maritn flowes",
  "category": "sofware",
  "isbn": "4462312312312321"
}

### Eliminar libro por id protegido
DELETE {{baseUrl}}/books/{{bookId}}
Authorization: Bearer {{token}}



//////////////////////////////////////////USERS//////////////////////////////////////////

### Listar perfiles protegido
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Actualizar o completar perfil protegido
PUT {{baseUrl}}/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fullName": "pedro torres",
  "phone": "4545343",
  "address": "santiago"
}

### Eliminar perfil protegido
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

//////////////////////////////////////////LOANS//////////////////////////////////////////

### Crear préstamo protegido
POST {{baseUrl}}/loans
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "{{userId}}",
  "bookId": "{{bookId}}"
}

### Obtener préstamo por id protegido
GET {{baseUrl}}/loans/{{loanId}}
Authorization: Bearer {{token}}

### Obtener préstamos por usuario protegido
GET {{baseUrl}}/loans/user/{{userId}}
Authorization: Bearer {{token}}

### Contar préstamos protegida
GET {{baseUrl}}/loans/count
Authorization: Bearer {{token}}

//////////////////////////////////////////RESERVATIONS//////////////////////////////////////////

### Crear reserva protegida
POST {{baseUrl}}/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "{{userId}}",
  "bookId": "{{bookId}}"
}

### Obtener reservas por usuario protegido
GET {{baseUrl}}/reservations/user/{{userId}}
Authorization: Bearer {{token}}

### Cancelar reserva protegida
DELETE {{baseUrl}}/reservations/{{bookId}}
Authorization: Bearer {{token}}

//////////////////////////////////////////RETURNS//////////////////////////////////////////

### Registrar devolución protegida
POST {{baseUrl}}/returns
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "loanId": "{{loanId}}"
}

### Obtener devolución por loanId protegido
GET {{baseUrl}}/returns/loan/{{loanId}}
Authorization: Bearer {{token}}

//////////////////////////////////////////FINES//////////////////////////////////////////

### Obtener multa por id protegida
GET {{baseUrl}}/fines/55555555-5555-5555-5555-555555555555
Authorization: Bearer {{token}}

### Obtener multas por usuario protegido
GET {{baseUrl}}/fines/user/{{userId}}
Authorization: Bearer {{token}}

### Pagar multa protegida
PATCH {{baseUrl}}/fines/55555555-5555-5555-5555-555555555555/pay
Authorization: Bearer {{token}}

### Contar multas protegida
GET {{baseUrl}}/fines/count
Authorization: Bearer {{token}}

### Contar multas pendientes protegida
GET {{baseUrl}}/fines/count/pending
Authorization: Bearer {{token}}

### Contar multas pagadas protegida
GET {{baseUrl}}/fines/count/paid
Authorization: Bearer {{token}}

//////////////////////////////////////////DASHBOARD//////////////////////////////////////////

### Obtener dashboard de usuario protegido
GET {{baseUrl}}/dashboard/user/{{userId}}
Authorization: Bearer {{token}}

### Obtener resumen general protegido
GET {{baseUrl}}/reports/general-summary
Authorization: Bearer {{token}}