spring.application.name=book

server.port=5001

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:3001/book}
spring.datasource.username=${DB_USERNAME:book}
spring.datasource.password=${DB_PASSWORD:book}
spring.datasource.driver-class-name=org.postgresql.Driver

# Show all logs for debugging purposes
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.example.booksusers=DEBUG

# Show SQL statements in the logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true