spring.application.name=auth

server.port=5003

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:3003/authdb}
spring.datasource.username=${AUTH_DB_USERNAME:authuser}
spring.datasource.password=${AUTH_DB_PASSWORD:authpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=${JWT_SECRET:mi_clave_super_secreta_muy_larga_12345678901234567890}
security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:24}
