spring.application.name=ms-fines

server.port=5007
spring.datasource.url=jdbc:postgresql://localhost:3007/fines
spring.datasource.username=fines
spring.datasource.password=fines

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
