spring.application.name=ms-reservations

server.port=5006

spring.datasource.url=jdbc:postgresql://localhost:3006/reservations
spring.datasource.username=reservations
spring.datasource.password=reservations

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

services.user.base-url=${USER_SERVICE_URL:http://localhost:5002}
services.book.base-url=${BOOK_SERVICE_URL:http://localhost:5001}
services.notification.base-url=${NOTIFICATION_SERVICE_URL:http://localhost:5008}