spring.application.name=bff
server.port=5000

auth.service.base-url=http://localhost:5003
user.service.base-url=http://localhost:5002
book.service.base-url=http://localhost:5001

springdoc.api-docs.version=OPENAPI_3_0

security.jwt.secret=mi_clave_super_secreta_muy_larga_12345678901234567890
security.jwt.expiration-hours=24