spring.application.name=bff

server.port=5000

auth.service.base-url=${AUTH_SERVICE_URL:http://localhost:5003}
user.service.base-url=${USER_SERVICE_URL:http://localhost:5002}
book.service.base-url=${BOOK_SERVICE_URL:http://localhost:5001}
loan.service.base-url=${LOAN_SERVICE_URL:http://localhost:5004}
return.service.base-url=${RETURN_SERVICE_URL:http://localhost:5005}
reservation.service.base-url=${RESERVATION_SERVICE_URL:http://localhost:5006}
fine.service.base-url=${FINE_SERVICE_URL:http://localhost:5007}
notification.service.base-url=${NOTIFICATION_SERVICE_URL:http://localhost:5008}
report.service.base-url=${REPORT_SERVICE_URL:http://localhost:5009}

springdoc.api-docs.version=OPENAPI_3_0

security.jwt.secret=${JWT_SECRET:mi_clave_super_secreta_muy_larga_12345678901234567890}
security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:24}

# =========================================
# GLITCHTIP / SENTRY
# =========================================

# Permite activar o desactivar GlitchTip mediante variable de entorno
sentry.enabled=${SENTRY_ENABLED:false}

# DSN entregado por GlitchTip
sentry.dsn=${SENTRY_DSN:}

# Ambiente mostrado dentro de GlitchTip
sentry.environment=${SENTRY_ENVIRONMENT:development}

# Versión del componente que generó el error
sentry.release=${SENTRY_RELEASE:eva-3-library-bff@1.0.0}

# No enviar información personal por defecto
sentry.send-default-pii=false

# No necesitamos monitoreo de rendimiento para el examen
sentry.traces-sample-rate=0.0

# Mostrar información interna del SDK solamente cuando sea necesario
sentry.debug=${SENTRY_DEBUG:false}