spring.application.name=ms-returns

server.port=5005

spring.datasource.url=jdbc:postgresql://localhost:3005/returns
spring.datasource.username=returns
spring.datasource.password=returns

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

services.loan.base-url=${LOAN_SERVICE_URL:http://localhost:5004}
services.book.base-url=${BOOK_SERVICE_URL:http://localhost:5001}
services.fine.base-url=${FINE_SERVICE_URL:http://localhost:5007}