spring.application.name=ms-returns

server.port=5005

spring.datasource.url=jdbc:postgresql://localhost:3005/returns
spring.datasource.username=returns
spring.datasource.password=returns

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration