spring.application.name=loans

server.port=5004

spring.datasource.url=jdbc:postgresql://localhost:3004/loans
spring.datasource.username=loans
spring.datasource.password=loans

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

services.user.base-url=${USER_SERVICE_URL:http://localhost:5002}
services.book.base-url=${BOOK_SERVICE_URL:http://localhost:5001}